/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = [''];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvanVuaW9yL0Rlc2Vudi9UaGUtQ29tcGxldGUtQW5ndWxhci1Db3Vyc2UtQmVnaW5uZXItdG8tQWR2YW5jZWQvZGVwbG95LWRlbW8vc3JjL2FwcC9hcHAuY29tcG9uZW50LmNzcy5zaGltLm5nc3R5bGUudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9ob21lL2p1bmlvci9EZXNlbnYvVGhlLUNvbXBsZXRlLUFuZ3VsYXItQ291cnNlLUJlZ2lubmVyLXRvLUFkdmFuY2VkL2RlcGxveS1kZW1vL3NyYy9hcHAvYXBwLmNvbXBvbmVudC5jc3MiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7OyJ9
